### LANGUAGE
GET http://{{host}}:{{vocabulary-port}}/{{languages-path}}/

###
GET http://{{host}}:{{vocabulary-port}}/{{languages-path}}/{{language-id}}

###
POST http://{{host}}:{{vocabulary-port}}/{{languages-path}}/
Content-Type: application/json

{
  "name": "English"
}

###
DELETE http://{{host}}:{{vocabulary-port}}/{{languages-path}}/{{language-id}}

### VOCABULARY ENTRY
GET http://{{host}}:{{vocabulary-port}}/{{vocabulary-entries-path}}/

###
POST http://{{host}}:{{vocabulary-port}}/{{vocabulary-entries-path}}/
Content-Type: application/json

{
  "name": "wade",
  "definition": "walk with effort",
  "languageId": "1",
  "synonyms": ["ford", "paddle"]
}

###
GET http://{{host}}:{{vocabulary-port}}/{{vocabulary-entries-path}}/5
