spring:
  datasource:
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres

vocabulary.entry.color.enabled: true

import:
  enabled: true
  progress.step: 10