###
GET http://{{host}}:{{notes-port}}/{{notes-path}}/

###
GET http://{{host}}:{{notes-port}}/{{notes-path}}/{{note-id}}

###
POST http://{{host}}:{{notes-port}}/{{notes-path}}/
Content-Type: application/json

{
  "content": "New Note"
}

###
DELETE http://{{host}}:{{notes-port}}/{{notes-path}}/{{note-id}}
