package mentalarithmetic

enum class ChallengeType {
    MULTIPLICATION,
    DIVISION,
    SUM_OR_SUBTRACTION_OF_MULTIPLICATIONS,
    SUM_OR_SUBTRACTION_OF_DIVISION_AND_MULTIPLICATION,
    SUM_OR_SUBTRACTION_OF_DIVISIONS,
}