###
GET http://{{host}}:{{port}}/notes/

###
GET http://{{host}}:{{port}}/notes/{{id}}

###
POST http://{{host}}:{{port}}/notes/
Content-Type: application/json

{
  "content": "New Note"
}

###
DELETE http://{{host}}:{{port}}/notes/{{id}}
